# Generated by Django 5.1.7 on 2025-03-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about_service_created_service_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
